'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
'     ランタイム バージョン:4.0.30319.42000
'
'     このファイルへの変更は、コードが再生成されると失われます。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Pages.Common

    Partial Public Class Login

        '''<summary>
        '''pnlLogin コントロール。
        '''</summary>
        '''<remarks>
        '''自動生成されたフィールド。
        '''変更するには、フィールドの宣言をデザイナー ファイルから分離コード ファイルに移動します。
        '''</remarks>
        Protected WithEvents pnlLogin As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblLoginCode コントロール。
        '''</summary>
        '''<remarks>
        '''自動生成されたフィールド。
        '''変更するには、フィールドの宣言をデザイナー ファイルから分離コード ファイルに移動します。
        '''</remarks>
        Protected WithEvents lblLoginCode As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtLoginCode コントロール。
        '''</summary>
        '''<remarks>
        '''自動生成されたフィールド。
        '''変更するには、フィールドの宣言をデザイナー ファイルから分離コード ファイルに移動します。
        '''</remarks>
        Protected WithEvents txtLoginCode As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''rfvLoginCode コントロール。
        '''</summary>
        '''<remarks>
        '''自動生成されたフィールド。
        '''変更するには、フィールドの宣言をデザイナー ファイルから分離コード ファイルに移動します。
        '''</remarks>
        Protected WithEvents rfvLoginCode As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''revLoginCode コントロール。
        '''</summary>
        '''<remarks>
        '''自動生成されたフィールド。
        '''変更するには、フィールドの宣言をデザイナー ファイルから分離コード ファイルに移動します。
        '''</remarks>
        Protected WithEvents revLoginCode As Global.System.Web.UI.WebControls.RegularExpressionValidator

        '''<summary>
        '''btnLogin コントロール。
        '''</summary>
        '''<remarks>
        '''自動生成されたフィールド。
        '''変更するには、フィールドの宣言をデザイナー ファイルから分離コード ファイルに移動します。
        '''</remarks>
        Protected WithEvents btnLogin As Global.System.Web.UI.WebControls.Button
    End Class
End Namespace
