'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
'     ランタイム バージョン:4.0.30319.42000
'
'     このファイルへの変更は、コードが再生成されると失われます。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Pages.Entry

    Partial Public Class InvoiceImport

        '''<summary>lblChumonsaki コントロール。</summary>
        '''<remarks>自動生成されたフィールド。</remarks>
        Protected WithEvents lblChumonsaki As Global.System.Web.UI.WebControls.Label

        '''<summary>rblChumonsaki コントロール。</summary>
        '''<remarks>自動生成されたフィールド。</remarks>
        Protected WithEvents rblChumonsaki As Global.System.Web.UI.WebControls.RadioButtonList

        '''<summary>lblTsuka コントロール。</summary>
        '''<remarks>自動生成されたフィールド。</remarks>
        Protected WithEvents lblTsuka As Global.System.Web.UI.WebControls.Label

        '''<summary>rblTsuka コントロール。</summary>
        '''<remarks>自動生成されたフィールド。</remarks>
        Protected WithEvents rblTsuka As Global.System.Web.UI.WebControls.RadioButtonList

        '''<summary>lblShanghaiChotatsu コントロール。</summary>
        '''<remarks>自動生成されたフィールド。</remarks>
        Protected WithEvents lblShanghaiChotatsu As Global.System.Web.UI.WebControls.Label

        '''<summary>ddlShanghaiChotatsu コントロール。</summary>
        '''<remarks>自動生成されたフィールド。</remarks>
        Protected WithEvents ddlShanghaiChotatsu As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>lblInvoiceFile コントロール。</summary>
        '''<remarks>自動生成されたフィールド。</remarks>
        Protected WithEvents lblInvoiceFile As Global.System.Web.UI.WebControls.Label

        '''<summary>fuInvoice コントロール。</summary>
        '''<remarks>自動生成されたフィールド。</remarks>
        Protected WithEvents fuInvoice As Global.System.Web.UI.WebControls.FileUpload

        '''<summary>lblPackingFile コントロール。</summary>
        '''<remarks>自動生成されたフィールド。</remarks>
        Protected WithEvents lblPackingFile As Global.System.Web.UI.WebControls.Label

        '''<summary>fuPacking コントロール。</summary>
        '''<remarks>自動生成されたフィールド。</remarks>
        Protected WithEvents fuPacking As Global.System.Web.UI.WebControls.FileUpload

        '''<summary>lblRefNo コントロール。</summary>
        '''<remarks>自動生成されたフィールド。</remarks>
        Protected WithEvents lblRefNo As Global.System.Web.UI.WebControls.Label

        '''<summary>txtRefNo コントロール。</summary>
        '''<remarks>自動生成されたフィールド。</remarks>
        Protected WithEvents txtRefNo As Global.System.Web.UI.WebControls.TextBox

        '''<summary>btnImport コントロール。</summary>
        '''<remarks>自動生成されたフィールド。</remarks>
        Protected WithEvents btnImport As Global.System.Web.UI.WebControls.Button

        '''<summary>btnRerun コントロール。</summary>
        '''<remarks>自動生成されたフィールド。</remarks>
        Protected WithEvents btnRerun As Global.System.Web.UI.WebControls.Button

        '''<summary>btnKakunin コントロール。</summary>
        '''<remarks>自動生成されたフィールド。</remarks>
        Protected WithEvents btnKakunin As Global.System.Web.UI.WebControls.Button

        '''<summary>pnlProcessing コントロール。</summary>
        '''<remarks>自動生成されたフィールド。</remarks>
        Protected WithEvents pnlProcessing As Global.System.Web.UI.WebControls.Panel

        '''<summary>pnlConfirm コントロール。</summary>
        '''<remarks>自動生成されたフィールド。</remarks>
        Protected WithEvents pnlConfirm As Global.System.Web.UI.WebControls.Panel

        '''<summary>litConfirmMessage コントロール。</summary>
        '''<remarks>自動生成されたフィールド。</remarks>
        Protected WithEvents litConfirmMessage As Global.System.Web.UI.WebControls.Literal

        '''<summary>btnConfirm1 コントロール。</summary>
        '''<remarks>自動生成されたフィールド。</remarks>
        Protected WithEvents btnConfirm1 As Global.System.Web.UI.WebControls.Button

        '''<summary>btnConfirm2 コントロール。</summary>
        '''<remarks>自動生成されたフィールド。</remarks>
        Protected WithEvents btnConfirm2 As Global.System.Web.UI.WebControls.Button

        '''<summary>btnConfirm3 コントロール。</summary>
        '''<remarks>自動生成されたフィールド。</remarks>
        Protected WithEvents btnConfirm3 As Global.System.Web.UI.WebControls.Button
    End Class
End Namespace
