'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Partial Public Class HeaderControl

    ''' <summary>divHeader コントロール。</summary>
    Protected WithEvents divHeader As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    ''' <summary>lblTitle コントロール。</summary>
    Protected WithEvents lblTitle As Global.System.Web.UI.WebControls.Label

    ''' <summary>lblName コントロール。</summary>
    Protected WithEvents lblName As Global.System.Web.UI.WebControls.Label

    ''' <summary>phButtons コントロール。</summary>
    Protected WithEvents phButtons As Global.System.Web.UI.WebControls.PlaceHolder
End Class
