'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Partial Public Class ExpenseCodeMaintenance

    ''' <summary>gvExpenseCode コントロール。</summary>
    Protected WithEvents gvExpenseCode As Global.System.Web.UI.WebControls.GridView

    ''' <summary>btnSave コントロール。</summary>
    Protected WithEvents btnSave As Global.System.Web.UI.WebControls.Button

    ''' <summary>btnReload コントロール。</summary>
    Protected WithEvents btnReload As Global.System.Web.UI.WebControls.Button
End Class
