'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
'     ランタイム バージョン:4.0.30319.42000
'
'     このファイルへの変更は、コードが再生成されると失われます。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Pages.Entry

    Partial Public Class ImportResult

        '''<summary>upnResult コントロール。</summary>
        '''<remarks>自動生成されたフィールド。</remarks>
        Protected WithEvents upnResult As Global.System.Web.UI.UpdatePanel

        '''<summary>lblInvoiceNo コントロール。</summary>
        '''<remarks>自動生成されたフィールド。</remarks>
        Protected WithEvents lblInvoiceNo As Global.System.Web.UI.WebControls.Label

        '''<summary>ddlInvoiceNo コントロール。</summary>
        '''<remarks>自動生成されたフィールド。</remarks>
        Protected WithEvents ddlInvoiceNo As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>lblCount コントロール。</summary>
        '''<remarks>自動生成されたフィールド。</remarks>
        Protected WithEvents lblCount As Global.System.Web.UI.WebControls.Label

        '''<summary>lnkTabInvoice コントロール。</summary>
        '''<remarks>自動生成されたフィールド。</remarks>
        Protected WithEvents lnkTabInvoice As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>lnkTabPacking コントロール。</summary>
        '''<remarks>自動生成されたフィールド。</remarks>
        Protected WithEvents lnkTabPacking As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>pnlInvoice コントロール。</summary>
        '''<remarks>自動生成されたフィールド。</remarks>
        Protected WithEvents pnlInvoice As Global.System.Web.UI.WebControls.Panel

        '''<summary>gvInvoice コントロール。</summary>
        '''<remarks>自動生成されたフィールド。</remarks>
        Protected WithEvents gvInvoice As Global.System.Web.UI.WebControls.GridView

        '''<summary>pnlPacking コントロール。</summary>
        '''<remarks>自動生成されたフィールド。</remarks>
        Protected WithEvents pnlPacking As Global.System.Web.UI.WebControls.Panel

        '''<summary>gvPacking コントロール。</summary>
        '''<remarks>自動生成されたフィールド。</remarks>
        Protected WithEvents gvPacking As Global.System.Web.UI.WebControls.GridView

        '''<summary>btnExcel コントロール。</summary>
        '''<remarks>自動生成されたフィールド。</remarks>
        Protected WithEvents btnExcel As Global.System.Web.UI.WebControls.Button
    End Class
End Namespace
