'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Partial Public Class _Default

    ''' <summary>rptBlocks コントロール。</summary>
    Protected WithEvents rptBlocks As Global.System.Web.UI.WebControls.Repeater
End Class
