'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Partial Public Class SiteMaster

    ''' <summary>cphHead コントロール。</summary>
    Protected WithEvents cphHead As Global.System.Web.UI.WebControls.ContentPlaceHolder

    ''' <summary>frmMain コントロール。</summary>
    Protected WithEvents frmMain As Global.System.Web.UI.HtmlControls.HtmlForm

    ''' <summary>smMain コントロール。</summary>
    Protected WithEvents smMain As Global.System.Web.UI.ScriptManager

    ''' <summary>hdrHeader コントロール。</summary>
    Protected WithEvents hdrHeader As Global.Atom.Web.HeaderControl

    ''' <summary>pnlMessage コントロール。</summary>
    Protected WithEvents pnlMessage As Global.System.Web.UI.WebControls.Panel

    ''' <summary>litMessage コントロール。</summary>
    Protected WithEvents litMessage As Global.System.Web.UI.WebControls.Literal

    ''' <summary>cphContent コントロール。</summary>
    Protected WithEvents cphContent As Global.System.Web.UI.WebControls.ContentPlaceHolder

    ''' <summary>btnReconnect コントロール。</summary>
    Protected WithEvents btnReconnect As Global.System.Web.UI.WebControls.Button

    ''' <summary>litVersion コントロール。</summary>
    Protected WithEvents litVersion As Global.System.Web.UI.WebControls.Literal
End Class
