Option Strict On
Option Explicit On

'------------------------------------------------------------------------------
' <auto-generated>
'     型付きデータセット（経費コードマスタ）。Visual Studio の DataSet デザイナーで
'     ExpenseDataSet.xsd を開くと、このコードは自動生成コードで置き換えられます。
' </auto-generated>
'------------------------------------------------------------------------------

<Global.System.Serializable(), _
 Global.System.ComponentModel.DesignerCategoryAttribute("code"), _
 Global.System.ComponentModel.ToolboxItem(True)> _
Partial Public Class ExpenseDataSet
    Inherits Global.System.Data.DataSet

    Private tableExpenseCode As ExpenseCodeDataTable

    Public Sub New()
        MyBase.New()
        Me.BeginInit()
        Me.InitClass()
        Me.EndInit()
    End Sub

    <Global.System.ComponentModel.Browsable(False)> _
    Public ReadOnly Property ExpenseCode() As ExpenseCodeDataTable
        Get
            Return Me.tableExpenseCode
        End Get
    End Property

    Private Sub InitClass()
        Me.DataSetName = "ExpenseDataSet"
        Me.tableExpenseCode = New ExpenseCodeDataTable()
        Me.Tables.Add(Me.tableExpenseCode)
    End Sub
End Class

<Global.System.Serializable()> _
Partial Public Class ExpenseCodeDataTable
    Inherits Global.System.Data.DataTable

    Public Sub New()
        MyBase.New()
        Me.TableName = "ExpenseCode"
        Me.InitClass()
    End Sub

    Private Sub InitClass()
        Me.Columns.Add(New Global.System.Data.DataColumn("pk_keihi_code", GetType(String)))
        Me.Columns.Add(New Global.System.Data.DataColumn("keihi_code_text", GetType(String)))
        Me.Columns.Add(New Global.System.Data.DataColumn("keihi_code_ref", GetType(String)))
        Me.Columns.Add(New Global.System.Data.DataColumn("keihi_kbn", GetType(String)))
        Me.Columns.Add(New Global.System.Data.DataColumn("hoken_taisyo_flg", GetType(String)))
        Me.Columns.Add(New Global.System.Data.DataColumn("update_ymd", GetType(String)))
        Me.Columns.Add(New Global.System.Data.DataColumn("update_login", GetType(String)))
    End Sub
End Class
